[package]
name = "kasa_exporter"
version = "0.2.0"
description = "Prometheus exporter for TP-Link kasa devices"
authors = ["Ivan Babrou <hello@ivan.computer>"]
repository = "https://github.com/bobrik/kasa_exporter"
license = "MIT"
edition = "2018"

[features]
default = []
kasa_debug = []

[dependencies]
clap = "2"
tokio = { version = "0.2", features = ["macros"] }
http = "0.2"
hyper = "0.13"
hyper-tls = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = "0.12"
prometheus = { version = "0.9", default-features = false }
uuid = { version = "0.7", features = ["v4"] }
